using AppMobileCPM.Areas.Admin.ViewModels;
using AppMobileCPM.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Globalization;
using System.Text;

namespace AppMobileCPM.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(AuthenticationSchemes = AdminAuthConstants.AuthenticationScheme)]
[Route("admin/conteudos")]
public sealed class SiteContentController : Controller
{
    private readonly IAdminSiteContentService _contentService;

    public SiteContentController(IAdminSiteContentService contentService)
    {
        _contentService = contentService;
    }

    [HttpGet("")]
    public IActionResult Index()
    {
        var items = _contentService
            .GetAll()
            .Select(item => new AdminSiteContentListItemViewModel
            {
                Id = item.Id,
                FriendlyName = SiteContentLabelHelper.BuildFriendlyName(item.Key, item.Description),
                Key = item.Key,
                Value = item.Value,
                ValuePreview = item.Value.Length <= 100 ? item.Value : $"{item.Value[..100]}...",
                Description = SiteContentLabelHelper.IsAutoGeneratedDescription(item.Description) ? string.Empty : item.Description,
                IsActive = item.IsActive,
                CreatedAt = item.CreatedAt,
                UpdatedAt = item.UpdatedAt
            })
            .OrderBy(item => item.FriendlyName, StringComparer.OrdinalIgnoreCase)
            .ToList();

        return View(new AdminSiteContentListViewModel
        {
            Items = items
        });
    }

    [HttpGet("{id:int}/json")]
    public IActionResult DetailsJson(int id)
    {
        var item = _contentService.GetById(id);
        if (item is null)
        {
            return NotFound();
        }

        return Json(new
        {
            id = item.Id,
            friendlyName = SiteContentLabelHelper.BuildFriendlyName(item.Key, item.Description),
            key = item.Key,
            value = item.Value,
            description = SiteContentLabelHelper.IsAutoGeneratedDescription(item.Description) ? string.Empty : item.Description,
            isActive = item.IsActive,
            createdAt = item.CreatedAt.ToString("dd/MM/yyyy HH:mm"),
            updatedAt = item.UpdatedAt?.ToString("dd/MM/yyyy HH:mm") ?? "-"
        });
    }

    [HttpPost("novo")]
    [ValidateAntiForgeryToken]
    public IActionResult Create(AdminSiteContentInputModel model)
    {
        if (string.IsNullOrWhiteSpace(model.Key))
        {
            var generatedKey = BuildBaseKey(model.Description, model.Value);
            model.Key = BuildUniqueKey(generatedKey);
        }

        if (!ModelState.IsValid)
        {
            TempData["AdminErrorMessage"] = "Preencha os campos obrigatorios para criar o conteudo.";
            return RedirectToAction(nameof(Index));
        }

        try
        {
            _contentService.Create(new AdminSiteContentUpsertRequest
            {
                Key = model.Key,
                Value = model.Value,
                Description = model.Description,
                IsActive = model.IsActive
            });
            TempData["AdminSuccessMessage"] = "Conteudo criado com sucesso.";
        }
        catch (SqlException ex) when (ex.Number is 2627 or 2601)
        {
            TempData["AdminErrorMessage"] = "Ja existe um conteudo semelhante. Ajuste o nome legivel e tente novamente.";
        }
        catch
        {
            TempData["AdminErrorMessage"] = "Nao foi possivel criar o conteudo.";
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost("editar")]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(AdminSiteContentInputModel model)
    {
        var current = _contentService.GetById(model.Id);
        if (current is null)
        {
            TempData["AdminErrorMessage"] = "Conteudo nao encontrado para atualizacao.";
            return RedirectToAction(nameof(Index));
        }

        if (!ModelState.IsValid || model.Id <= 0)
        {
            TempData["AdminErrorMessage"] = "Dados invalidos para atualizar o conteudo.";
            return RedirectToAction(nameof(Index));
        }

        try
        {
            var updated = _contentService.Update(model.Id, new AdminSiteContentUpsertRequest
            {
                Key = current.Key,
                Value = model.Value,
                Description = model.Description,
                IsActive = model.IsActive
            });

            TempData["AdminSuccessMessage"] = updated
                ? "Conteudo atualizado com sucesso."
                : "Conteudo nao encontrado para atualizacao.";
        }
        catch (SqlException ex) when (ex.Number is 2627 or 2601)
        {
            TempData["AdminErrorMessage"] = "Ja existe um conteudo semelhante. Ajuste o nome legivel e tente novamente.";
        }
        catch
        {
            TempData["AdminErrorMessage"] = "Nao foi possivel atualizar o conteudo.";
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost("excluir")]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int id)
    {
        if (id <= 0)
        {
            TempData["AdminErrorMessage"] = "Conteudo invalido para exclusao.";
            return RedirectToAction(nameof(Index));
        }

        var deleted = _contentService.Delete(id);
        TempData["AdminSuccessMessage"] = deleted
            ? "Conteudo excluido com sucesso."
            : "Conteudo nao encontrado para exclusao.";

        return RedirectToAction(nameof(Index));
    }

    private string BuildUniqueKey(string baseKey)
    {
        var existingKeys = _contentService
            .GetAll()
            .Select(item => item.Key)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var candidate = Truncate(baseKey, 120);
        if (!existingKeys.Contains(candidate))
        {
            return candidate;
        }

        var suffix = 2;
        while (true)
        {
            var suffixText = $".{suffix}";
            var prefixLimit = 120 - suffixText.Length;
            var prefixed = $"{Truncate(baseKey, prefixLimit)}{suffixText}";
            if (!existingKeys.Contains(prefixed))
            {
                return prefixed;
            }

            suffix++;
        }
    }

    private static string BuildBaseKey(string description, string value)
    {
        var token = BuildToken(description);
        if (string.IsNullOrWhiteSpace(token))
        {
            var valueSource = value?.Trim() ?? string.Empty;
            if (valueSource.StartsWith("data:image/", StringComparison.OrdinalIgnoreCase))
            {
                token = "imagem";
            }
            else
            {
                if (valueSource.Length > 300)
                {
                    valueSource = valueSource[..300];
                }

                token = BuildToken(valueSource);
            }
        }

        if (string.IsNullOrWhiteSpace(token))
        {
            token = "conteudo";
        }

        return $"content.{token}";
    }

    private static string BuildToken(string rawText)
    {
        if (string.IsNullOrWhiteSpace(rawText))
        {
            return string.Empty;
        }

        var asciiText = RemoveDiacritics(rawText).ToLowerInvariant();
        var builder = new StringBuilder(asciiText.Length);
        var previousWasSeparator = false;

        foreach (var character in asciiText)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(character);
                previousWasSeparator = false;
                continue;
            }

            if (previousWasSeparator)
            {
                continue;
            }

            builder.Append('-');
            previousWasSeparator = true;
        }

        var normalized = builder.ToString().Trim('-');
        return Truncate(normalized, 100);
    }

    private static string RemoveDiacritics(string text)
    {
        var normalized = text.Normalize(NormalizationForm.FormD);
        var builder = new StringBuilder(normalized.Length);

        foreach (var character in normalized)
        {
            var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(character);
            if (unicodeCategory != UnicodeCategory.NonSpacingMark)
            {
                builder.Append(character);
            }
        }

        return builder.ToString().Normalize(NormalizationForm.FormC);
    }

    private static string Truncate(string value, int maxLength)
    {
        if (string.IsNullOrEmpty(value) || value.Length <= maxLength)
        {
            return value;
        }

        return value[..maxLength];
    }
}
