namespace AppMobileCPM.Services;

public static class SiteContentLabelHelper
{
    private static readonly IReadOnlyDictionary<string, string> TokenMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["home"] = "Home",
        ["hero"] = "Hero",
        ["about"] = "Sobre",
        ["proposal"] = "Proposta",
        ["differentials"] = "Diferenciais",
        ["topservices"] = "Servicos mais buscados",
        ["howitworks"] = "Como funciona",
        ["procta"] = "CTA profissional",
        ["finalcta"] = "CTA final",
        ["title"] = "Titulo",
        ["subtitle"] = "Subtitulo",
        ["paragraph1"] = "Paragrafo 1",
        ["paragraph2"] = "Paragrafo 2",
        ["legal"] = "Documentos legais",
        ["professional"] = "Profissionais",
        ["privacy"] = "Privacidade",
        ["html"] = "HTML"
    };

    public static bool IsAutoGeneratedDescription(string? description)
    {
        if (string.IsNullOrWhiteSpace(description))
        {
            return true;
        }

        return description.StartsWith("Conteudo editavel da chave ", StringComparison.OrdinalIgnoreCase);
    }

    public static string BuildFriendlyName(string key, string? description)
    {
        if (!string.IsNullOrWhiteSpace(description) && !IsAutoGeneratedDescription(description))
        {
            return description.Trim();
        }

        var tokens = key.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (tokens.Length == 0)
        {
            return "Conteudo sem identificador";
        }

        var readableTokens = tokens.Select(ToReadableToken);
        return string.Join(" > ", readableTokens);
    }

    private static string ToReadableToken(string token)
    {
        if (TokenMap.TryGetValue(token, out var mapped))
        {
            return mapped;
        }

        return char.ToUpperInvariant(token[0]) + token[1..];
    }
}
