namespace AppMobileCPM.Services;

public static class SiteContentLabelHelper
{
    private static readonly IReadOnlyDictionary<string, string> WordMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["faq"] = "FAQ",
        ["seo"] = "SEO",
        ["og"] = "OG",
        ["cta"] = "CTA",
        ["url"] = "URL",
        ["id"] = "ID",
        ["cep"] = "CEP",
        ["html"] = "HTML"
    };

    private static readonly IReadOnlyDictionary<string, string> TokenMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["home"] = "Home",
        ["layout"] = "Layout",
        ["branding"] = "Marca",
        ["meta"] = "SEO",
        ["schema"] = "Schema",
        ["request"] = "Solicitar servico",
        ["register"] = "Cadastro profissional",
        ["professionals"] = "Profissionais",
        ["support"] = "Suporte",
        ["terms"] = "Termos de uso",
        ["privacy"] = "Privacidade",
        ["error"] = "Erro",
        ["hero"] = "Hero",
        ["about"] = "Sobre",
        ["proposal"] = "Proposta",
        ["differentials"] = "Diferenciais",
        ["topservices"] = "Servicos mais buscados",
        ["howitworks"] = "Como funciona",
        ["procta"] = "CTA profissional",
        ["finalcta"] = "CTA final",
        ["title"] = "Titulo",
        ["subtitle"] = "Subtitulo",
        ["paragraph1"] = "Paragrafo 1",
        ["paragraph2"] = "Paragrafo 2",
        ["legal"] = "Documentos legais",
        ["professional"] = "Profissionais",
        ["privacy"] = "Privacidade",
        ["html"] = "HTML"
    };

    public static bool IsAutoGeneratedDescription(string? description)
    {
        if (string.IsNullOrWhiteSpace(description))
        {
            return true;
        }

        return description.StartsWith("Conteudo editavel da chave ", StringComparison.OrdinalIgnoreCase);
    }

    public static string BuildFriendlyName(string key, string? description)
    {
        if (!string.IsNullOrWhiteSpace(description) && !IsAutoGeneratedDescription(description))
        {
            return description.Trim();
        }

        var tokens = key.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (tokens.Length == 0)
        {
            return "Conteudo sem identificador";
        }

        var readableTokens = tokens.Select(ToReadableToken);
        return string.Join(" > ", readableTokens);
    }

    private static string ToReadableToken(string token)
    {
        if (TokenMap.TryGetValue(token, out var mapped))
        {
            return mapped;
        }

        var words = token
            .Split(['_', '-', ' '], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(ToReadableWord)
            .ToArray();

        if (words.Length == 0)
        {
            return "Conteudo";
        }

        return string.Join(" ", words);
    }

    private static string ToReadableWord(string word)
    {
        if (WordMap.TryGetValue(word, out var mapped))
        {
            return mapped;
        }

        return word.Length == 1
            ? word.ToUpperInvariant()
            : char.ToUpperInvariant(word[0]) + word[1..];
    }
}
